# Generated by Django 5.1.4 on 2024-12-31 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HouseworkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('scale', models.IntegerField(default=3)),
                ('note', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housework.contributor')),
            ],
        ),
    ]
