# Generated by Django 5.1.4 on 2024-12-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseworkrecord',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
