# Generated by Django 5.1.4 on 2024-12-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0002_alter_houseworkrecord_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseworkrecord',
            old_name='scale',
            new_name='points',
        ),
    ]
