# Generated by Django 5.1.4 on 2025-01-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0005_reset_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseworkrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
